<script setup lang="ts">
import { reactive, watch } from 'vue'; import type { DiagnosisResult, ReviewRequest } from '../../types/diagnosis'
const props = defineProps<{ modelValue: boolean; result: DiagnosisResult; version: number; loading?: boolean }>(); const emit = defineEmits<{ 'update:modelValue': [value: boolean]; submit: [payload: ReviewRequest] }>()
const form = reactive({ clinical_summary: '', risk_level: 'low' as DiagnosisResult['risk_level'], recommended_department: '', recommended_tests: '', reason: '', conditions: [] as DiagnosisResult['possible_conditions'] })
watch(() => props.modelValue, (open) => { if (!open) return; form.clinical_summary = props.result.clinical_summary; form.risk_level = props.result.risk_level; form.recommended_department = props.result.recommended_department; form.recommended_tests = props.result.recommended_tests.join('\n'); form.reason = ''; form.conditions = props.result.possible_conditions.map(i => ({ ...i })) })
function submit() { const edited_result: DiagnosisResult = { ...props.result, clinical_summary: form.clinical_summary, risk_level: form.risk_level, recommended_department: form.recommended_department, recommended_tests: form.recommended_tests.split('\n').map(i => i.trim()).filter(Boolean), possible_conditions: form.conditions.map(i => ({ ...i })) }; emit('submit', { action: 'edit', expected_version: props.version, edited_result, reason: form.reason || undefined }) }
</script>
<template><el-drawer :model-value="modelValue" title="编辑诊断意见" size="min(720px, 94vw)" destroy-on-close @update:model-value="emit('update:modelValue', $event)"><div class="review-form"><el-alert title="医生修改将作为最终意见保存，AI 原始草稿会完整保留用于复盘。" type="info" :closable="false" /><el-form label-position="top"><el-form-item label="临床摘要"><el-input v-model="form.clinical_summary" type="textarea" :rows="5" /></el-form-item><div class="form-row"><el-form-item label="风险等级"><el-select v-model="form.risk_level"><el-option label="低风险" value="low" /><el-option label="中风险" value="medium" /><el-option label="高风险" value="high" /><el-option label="紧急风险" value="emergency" /></el-select></el-form-item><el-form-item label="建议科室"><el-input v-model="form.recommended_department" /></el-form-item></div><el-form-item label="鉴别诊断"><div class="condition-edit" v-for="(item, index) in form.conditions" :key="index"><el-input v-model="item.name" placeholder="诊断方向" /><el-input v-model="item.reason" type="textarea" :rows="2" placeholder="判断依据" /></div></el-form-item><el-form-item label="建议检查（每行一项）"><el-input v-model="form.recommended_tests" type="textarea" :rows="4" /></el-form-item><el-form-item label="医生补充意见"><el-input v-model="form.reason" type="textarea" :rows="3" placeholder="记录修改依据或补充说明" /></el-form-item></el-form></div><template #footer><el-button @click="emit('update:modelValue', false)">取消</el-button><el-button type="primary" :loading="loading" @click="submit">提交修改并确认</el-button></template></el-drawer></template>
<style scoped lang="scss">.review-form { display: grid; gap: 20px; }.form-row { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; }.condition-edit { width: 100%; display: grid; grid-template-columns: .75fr 1.5fr; gap: 8px; padding: 10px; background: var(--soft-surface); border-radius: 9px; margin-bottom: 8px; }@media (max-width: 640px) { .form-row, .condition-edit { grid-template-columns: 1fr; } }</style>
