<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { ElMessage } from 'element-plus'
import PatientHeader from '../../components/clinical/PatientHeader.vue'; import PatientSummary from '../../components/clinical/PatientSummary.vue'; import ClinicalTimeline from '../../components/clinical/ClinicalTimeline.vue'; import AllergyAlert from '../../components/clinical/AllergyAlert.vue'; import MedicationList from '../../components/clinical/MedicationList.vue'; import LabTable from '../../components/clinical/LabTable.vue'; import EmptyState from '../../components/common/EmptyState.vue'; import ErrorState from '../../components/common/ErrorState.vue'
import { getAllergies, getImaging, getLabs, getMedications, getPatient, getPatientOverview, getVisits } from '../../api/patient'; import { createDiagnosis } from '../../api/diagnosis'; import { getCases } from '../../api/case'; import type { Allergy, ImagingReport, LabResult, Medication, PatientOverview, PatientSummary as Summary, Visit } from '../../types/patient'; import type { MedicalCase } from '../../types/case'; import { formatDateTime } from '../../utils/format'; import { apiErrorMessage } from '../../utils/request'
const route = useRoute(); const router = useRouter(); const patientId = computed(() => String(route.params.patientId)); const patient = ref<Summary | null>(null); const overview = ref<PatientOverview | null>(null); const loading = ref(true); const error = ref(''); const active = ref('overview'); const loaded = new Set<string>(); const visits = ref<Visit[]>([]); const labs = ref<LabResult[]>([]); const imaging = ref<ImagingReport[]>([]); const medications = ref<Medication[]>([]); const allergies = ref<Allergy[]>([]); const cases = ref<MedicalCase[]>([]); const dialog = ref(false); const question = ref(''); const creating = ref(false)
// 首屏并行读取患者摘要和概览，减少进入档案页的等待时间。
async function loadBase() { loading.value = true; error.value = ''; try { [patient.value, overview.value] = await Promise.all([getPatient(patientId.value), getPatientOverview(patientId.value)]); loaded.add('overview') } catch { error.value = '患者临床档案加载失败' } finally { loading.value = false } }
// 按标签懒加载临床分类，成功后缓存标签，失败时移除缓存以便重试。
async function loadTab(name: string) { if (loaded.has(name)) return; loaded.add(name); try { if (name === 'visits') visits.value = await getVisits(patientId.value); if (name === 'labs') labs.value = await getLabs(patientId.value); if (name === 'imaging') imaging.value = await getImaging(patientId.value); if (name === 'medications') medications.value = await getMedications(patientId.value); if (name === 'allergies') allergies.value = await getAllergies(patientId.value); if (name === 'cases') cases.value = (await getCases({ page: 1, page_size: 20, search: patientId.value })).items } catch (e) { loaded.delete(name); ElMessage.error(apiErrorMessage(e, '分类数据加载失败')) } }
// 提交诊断前先做最小长度校验，成功后跳转到病例工作台查看实时进度。
async function startDiagnosis() { if (question.value.trim().length < 3) return ElMessage.warning('请填写本次需要辅助分析的临床问题'); creating.value = true; try { const created = await createDiagnosis(patientId.value, question.value.trim()); dialog.value = false; await router.push(`/cases/${created.case_id}`) } catch (e) { ElMessage.error(apiErrorMessage(e, '无法创建 AI 病例')) } finally { creating.value = false } }
watch(active, loadTab); onMounted(loadBase)
</script>
<template><main class="page-shell"><el-skeleton v-if="loading" :rows="9" animated /><ErrorState v-else-if="error" :message="error" @retry="loadBase" /><template v-else-if="patient && overview"><PatientHeader class="surface" :patient="patient"><el-button type="primary" @click="dialog = true">发起 AI 辅助诊断</el-button></PatientHeader>
  <section class="surface patient-tabs"><el-tabs v-model="active"><el-tab-pane label="概览" name="overview"><div class="overview-grid"><PatientSummary :overview="overview" /><ClinicalTimeline :visits="overview.recent_visits" /><div class="alerts"><AllergyAlert :items="overview.allergies" /><article class="reminder"><h3>近期重要异常</h3><div v-if="overview.recent_labs.some(i => i.abnormal_flag !== 'normal')"><p v-for="item in overview.recent_labs.filter(i => i.abnormal_flag !== 'normal')" :key="item.id">{{ item.test_name }}：{{ item.value }}</p></div><p v-else>暂无近期重要异常记录</p></article></div></div></el-tab-pane>
  <el-tab-pane label="就诊记录" name="visits"><el-timeline v-if="visits.length"><el-timeline-item v-for="item in visits" :key="item.id" :timestamp="formatDateTime(item.visit_time)"><strong>{{ item.department }}</strong><p>{{ item.chief_complaint }}</p></el-timeline-item></el-timeline><EmptyState v-else title="暂无就诊记录" /></el-tab-pane>
  <el-tab-pane label="检验" name="labs"><LabTable v-if="labs.length" :items="labs" /><EmptyState v-else title="暂无检验记录" /></el-tab-pane>
  <el-tab-pane label="影像" name="imaging"><div v-if="imaging.length" class="report-list"><article v-for="item in imaging" :key="item.id"><header><strong>{{ item.modality }} · {{ item.body_part }}</strong><time>{{ formatDateTime(item.observed_at) }}</time></header><p>{{ item.findings }}</p><div>影像印象：{{ item.impression }}</div></article></div><EmptyState v-else title="暂无近期影像检查" /></el-tab-pane>
  <el-tab-pane label="用药" name="medications"><MedicationList :items="medications" /></el-tab-pane><el-tab-pane label="过敏" name="allergies"><AllergyAlert :items="allergies" /></el-tab-pane>
  <el-tab-pane label="AI 病例" name="cases"><el-table v-if="cases.length" :data="cases"><el-table-column prop="id" label="病例号" min-width="220" /><el-table-column prop="question" label="主诉 / 临床问题" min-width="260" /><el-table-column prop="status" label="状态" width="130" /><el-table-column width="100"><template #default="{ row }"><el-button link type="primary" @click="router.push(`/cases/${row.id}`)">进入病例</el-button></template></el-table-column></el-table><EmptyState v-else title="暂无 AI 辅助诊断记录" /></el-tab-pane></el-tabs></section></template>
  <el-dialog v-model="dialog" title="发起 AI 辅助诊断" width="min(620px, 92vw)"><p class="dialog-note">请描述本次就诊的主诉、关键症状和需要 AI 辅助分析的问题。系统会读取该患者已授权的临床资料，并在医生审核前保持为 AI 草稿。</p><el-input v-model="question" type="textarea" :rows="6" maxlength="4000" show-word-limit placeholder="例如：患者活动后胸痛 2 天，有高血压史，请进行风险筛查并给出鉴别方向。" /><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" :loading="creating" @click="startDiagnosis">开始 AI 分析</el-button></template></el-dialog></main></template>
<style scoped lang="scss">.patient-tabs { padding: 0 22px 24px; margin-top: 16px; }.overview-grid { display: grid; grid-template-columns: 1fr 1.15fr .85fr; gap: 16px; padding: 8px 2px 4px; }.alerts { display: grid; align-content: start; gap: 14px; }.reminder { padding: 18px; background: var(--soft-surface); border-radius: var(--radius); }.reminder h3 { margin: 0 0 12px; font-size: 14px; }.reminder p { color: var(--text-secondary); font-size: 12px; }.report-list { display: grid; gap: 12px; }.report-list article { padding: 18px; border: 1px solid var(--border); border-radius: 10px; }.report-list header { display: flex; justify-content: space-between; }.report-list time { color: var(--text-tertiary); font-size: 11px; }.report-list p { color: var(--text-secondary); line-height: 1.6; }.report-list div { background: var(--soft-surface); padding: 10px; border-radius: 8px; font-size: 13px; }.dialog-note { color: var(--text-secondary); font-size: 13px; line-height: 1.65; margin-top: 0; }@media (max-width: 1200px) { .overview-grid { grid-template-columns: 1fr 1fr; }.alerts { grid-column: 1 / -1; grid-template-columns: 1fr 1fr; } }@media (max-width: 760px) { .overview-grid, .alerts { grid-template-columns: 1fr; }.alerts { grid-column: auto; } }</style>
